name = "Brute"
uuid = "752f060d-3016-44c4-afc7-6964a0c7390d"
authors = ["Kunz-David <epicfail.davidkunz@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
